CREATE TYPE [dbo].[NewEquitiesDataType] AS TABLE (
    [SimFinId]                         INT           NULL,
    [Ticker]                           NVARCHAR (10) NULL,
    [Date]                             DATE          NULL,
    [Open]                             FLOAT (53)    NULL,
    [High]                             FLOAT (53)    NULL,
    [Low]                              FLOAT (53)    NULL,
    [Close]                            FLOAT (53)    NULL,
    [AdjClose]                         FLOAT (53)    NULL,
    [Volume]                           BIGINT        NULL,
    [Dividend]                         FLOAT (53)    NULL,
    [SharesOutstanding]                FLOAT (53)    NULL,
    [MarketCap]                        FLOAT (53)    NULL,
    [PriceToEarningsQuarterly]         FLOAT (53)    NULL,
    [PriceToEarningsTTM]               FLOAT (53)    NULL,
    [PriceToSalesQuarterly]            FLOAT (53)    NULL,
    [PriceToSalesTTM]                  FLOAT (53)    NULL,
    [PriceToBookValue]                 FLOAT (53)    NULL,
    [PriceToFreeCashFlowQuarterly]     FLOAT (53)    NULL,
    [PriceToFreeCashFlowTTM]           FLOAT (53)    NULL,
    [EnterpriseValue]                  FLOAT (53)    NULL,
    [EnterpriseValueToEBITDA]          FLOAT (53)    NULL,
    [EnterpriseValueToSales]           FLOAT (53)    NULL,
    [EnterpriseValueToFreeCashFlow]    FLOAT (53)    NULL,
    [BookToMarketValue]                FLOAT (53)    NULL,
    [OperatingIncomeToEnterpriseValue] FLOAT (53)    NULL,
    [AltmanZScore]                     FLOAT (53)    NULL,
    [DividendYield]                    FLOAT (53)    NULL,
    [PriceToEarningsAdjusted]          FLOAT (53)    NULL);

